<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 2008 R2" host="USSLTCSNW2355"><DocLocation><![CDATA[D:\ITSS\Test_Automation_Framework\05_Test_Scripts\Main]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Main]]></DName>
<Res><![CDATA[Main]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [Flight_Login_Windows]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Setting the value 'admin' in the WinEdit Name : '']]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<NodeArgs eType="User" icon="8" nRep="12" status="Passed" >
<Disp><![CDATA[Setting the value 'admin' in the WinEdit Name : '']]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["50ab4aca0453a8678b3c3b3743b6158c9ad9fbeb"]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1 [Flight_Login_Windows]" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1 [Flight_Login_Windows]" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[WinButton Name: ''
Operation : Click]]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:13]]></Time>
<TimeTick>1353586393</TimeTick>
<NodeArgs eType="User" icon="8" nRep="18" status="Passed" >
<Disp><![CDATA[WinButton Name: ''
Operation : Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2012 - 7:13:13" eTime="11/22/2012 - 7:13:13" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 [Flight_Login_Windows] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[Action1 [Flight_Search_Windows]]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:15]]></Time>
<TimeTick>1353586395</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:15]]></Time>
<TimeTick>1353586395</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 6]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="25" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[MaskEdBox.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["12/12/12"]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="27" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[MaskEdBox.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Fly From:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="29" >
<Disp><![CDATA[Fly From:.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="22" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[WinComboBox Name ''
Operation : Select]]></Obj>
<Details ><![CDATA[The value 'Los Angeles' selected Successfully]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<NodeArgs eType="User" icon="8" nRep="30" status="Passed" >
<Disp><![CDATA[WinComboBox Name ''
Operation : Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Fly To:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:17]]></Time>
<TimeTick>1353586397</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="33" >
<Disp><![CDATA[Fly To:.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="32" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[WinComboBox Name ''
Operation : Select]]></Obj>
<Details ><![CDATA[The value 'Denver' selected Successfully]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="User" icon="8" nRep="34" status="Passed" >
<Disp><![CDATA[WinComboBox Name ''
Operation : Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" >
<Disp><![CDATA[FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="36" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[WinButton Name: ''
Operation : Click]]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="User" icon="8" nRep="38" status="Passed" >
<Disp><![CDATA[WinButton Name: ''
Operation : Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Flights Table]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[From.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA["4098   LAX   04:16 PM   DEN   05:14 PM   TWA   $124.20"]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="42" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[From.Activate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flights Table]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="40" Source="Action1 [Flight_Search_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2012 - 7:13:13" eTime="11/22/2012 - 7:13:18" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="20" status="Passed" >
<Disp><![CDATA[Action1 [Flight_Search_Windows] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[Action1 [Flight_Book_Windows]]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="Action1 [Flight_Book_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" >
<Disp><![CDATA[Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="46" Source="Action1 [Flight_Book_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Setting the value 'Kshama Pawar' in the WinEdit Name : '']]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="User" icon="8" nRep="50" status="Passed" >
<Disp><![CDATA[Setting the value 'Kshama Pawar' in the WinEdit Name : '']]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Tickets:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" >
<Disp><![CDATA[Tickets:.SetText]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="52" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[Setting the value '2' in the WinEdit Name : '']]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="User" icon="8" nRep="54" status="Passed" >
<Disp><![CDATA[Setting the value '2' in the WinEdit Name : '']]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Insert Order.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" >
<Disp><![CDATA[Insert Order.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="56" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[WinButton Name: ''
Operation : Click]]></Obj>
<Details ><![CDATA[Successful]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:18]]></Time>
<TimeTick>1353586398</TimeTick>
<NodeArgs eType="User" icon="8" nRep="58" status="Passed" >
<Disp><![CDATA[WinButton Name: ''
Operation : Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2012 - 7:13:18" eTime="11/22/2012 - 7:13:19" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="44" status="Passed" >
<Disp><![CDATA[Action1 [Flight_Book_Windows] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T40">
<AName><![CDATA[Action1 [Flight_LogOut_Windows]]]></AName>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:26]]></Time>
<TimeTick>1353586406</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:26]]></Time>
<TimeTick>1353586406</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" Source="Action1 [Flight_LogOut_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:26]]></Time>
<TimeTick>1353586406</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="65" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="62" Source="Action1 [Flight_LogOut_Windows]" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[WinMenu Name ''
Operation : Select]]></Obj>
<Details ><![CDATA[The value 'File;Exit' selected Successfully]]></Details>
<Time><![CDATA[11/22/2012 - 7:13:26]]></Time>
<TimeTick>1353586406</TimeTick>
<NodeArgs eType="User" icon="8" nRep="66" status="Passed" >
<Disp><![CDATA[WinMenu Name ''
Operation : Select]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/22/2012 - 7:13:19" eTime="11/22/2012 - 7:13:26" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="60" status="Passed" >
<Disp><![CDATA[Action1 [Flight_LogOut_Windows] Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="11/22/2012 - 7:13:12" eTime="11/22/2012 - 7:13:27" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Main Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="11/22/2012 - 7:13:12" eTime="11/22/2012 - 7:13:27" passed="9" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Main Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>